<?php

/**
 * @file
 * Main functions and hook implementations of the Calculator module.
 */

/**
 * Implements hook_menu().
 */
function calculator_menu() {
  $items = array();
  $items['calculator'] = array(
    'title' => t('Calculator'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('calculator_form'),
    'access arguments' => array('access content'),
    'description' => t('Perform calculation between entered fields'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}


/**
 * Form constructor for the Calculator form.
 *
 * @see calculator_form_validate()
 * @see calculator_form_add_submit()
 * @see calculator_form_division_submit()
 * @see calculator_form_multiplication_submit()
 * @see calculator_form_subtraction_submit()
 *
 * @ingroup forms
 */
function calculator_form($form, &$form_state) {

  $form['first_number'] = array(
    '#type' => 'textfield',
    '#title' => t('Value 1'),
    '#description' => "Please enter your first number.",
    '#required' => TRUE,
    '#size' => 5,
    '#maxlength' => 5,
     );

  $form['second_number'] = array(
    '#type' => 'textfield',
    '#title' => t('Value 2'),
    '#description' => "Please enter your second number.",
    '#required' => TRUE,
    '#size' => 5,
    '#maxlength' => 5,
   );

  $form['submit_add'] = array(
    '#type' => 'submit',
    '#value' => t('Sum'),
    '#submit' => array('calculator_form_addition_submit'),
    '#validate' => array('calculator_form_validate'),
  );

  $form['submit_multiply'] = array(
    '#type' => 'submit',
    '#value' => t('Product'),
    '#submit' => array('calculator_form_multiply_submit'),
    '#validate' => array('calculator_form_validate'),
 );

  $form['submit_substraction'] = array(
    '#type' => 'submit',
    '#value' => t('Subtraction'),
    '#submit' => array('calculator_form_substraction_submit'),
    '#validate' => array('calculator_form_validate'),
 );

  $form['submit_division'] = array(
    '#type' => 'submit',
    '#value' => t('Division'),
    '#submit' => array('calculator_form_division_submit'),
    '#validate' => array('calculator_form_validate'),
 );

  
  return $form;
}

/**
 * Form submission handler for calculator_form().
 *
 * Fires when the 'addition' submit button is pressed.
 */
function calculator_form_addition_submit($form, &$form_state) {

    $total = $form_state['values']['first_number'] + $form_state['values']['second_number'];
    drupal_set_message(t('The result is @total', array('@total' => $total)));

}

/**
 * Form submission handler for calculator_form().
 *
 * Fires when the 'multiplication' submit button is pressed.
 */
function calculator_form_multiply_submit($form, &$form_state) {

    $total = $form_state['values']['first_number'] * $form_state['values']['second_number'];
    drupal_set_message(t('The result is @total', array('@total' => $total)));

}

/**
 * Form submission handler for calculator_form().
 *
 * Fires when the 'division' submit button is pressed.
 */
function calculator_form_division_submit($form, &$form_state) {

    $total = $form_state['values']['first_number'] / $form_state['values']['second_number'];
    drupal_set_message(t('The result is @total', array('@total' => $total)));

}

/**
 * Form submission handler for calculator_form().
 *
 * Fires when the 'subtraction' submit button is pressed.
 */
function calculator_form_substraction_submit($form, &$form_state) {

    $total = $form_state['values']['first_number'] - $form_state['values']['second_number'];
    drupal_set_message(t('The result is @total', array('@total' => $total)));

}

/**
 * Form validation handler for calculator_form().
 */
function calculator_form_validate($form, &$form_state) {

    $first_number = $form_state['values']['first_number'];
    $second_number = $form_state['values']['second_number'];
    if (!empty($first_number) && !is_numeric($first_number)) {
        form_set_error('first', 'Only enter numeric values.');
    }
    if (!empty($second_number) && !is_numeric($second_number)) {
        form_set_error('second', 'Only enter numeric values.');
    }
}
